spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatistest
    username: root
    password: root
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  mail:
    host: smtp.163.com
    username: m15066283823@163.com
    password: fulin19980526


mybatis:
  type-aliases-package: com.fulin.pojo

pagehelper:
  helper-dialect: mysql
